
export const ForecastControlsActionType = {
  GET_FORECAST_CONTROLS: 'GET_FORECAST_CONTROLS',
  SET_FORECAST_CONTROLS: 'SET_FORECAST_CONTROLS',
  GET_FORECAST_CONTROLS_ERROR: 'GET_FORECAST_CONTROLS_ERROR',
  UPDATE_FORECAST_CONTROLS_STATE: 'UPDATE_FORECAST_CONTROLS_STATE',
  SAVE_FORECAST_CONTROLS: 'SAVE_FORECAST_CONTROLS',
  SAVE_FORECAST_CONTROLS_SUCCESS: 'SAVE_FORECAST_CONTROLS_SUCCESS',
  SAVE_FORECAST_CONTROLS_ERROR: 'SAVE_FORECAST_CONTROLS_ERROR',
  GET_HOLIDAYS_BY_LOCATION_ID: 'GET_HOLIDAYS_BY_LOCATION_ID',
  GET_HOLIDAYS_BY_LOCATION_ID_SUCCESS: 'GET_HOLIDAYS_BY_LOCATION_ID_SUCCESS',
  GET_HOLIDAYS_BY_LOCATION_ID_ERROR: 'GET_HOLIDAYS_BY_LOCATION_ID_ERROR',
  ADD_LOCATION_IN_CONTROLS_STATE: 'ADD_LOCATION_IN_CONTROLS_STATE'
};