export const GlobalActionType = {
  TOGGLE_LOADING_SPINNER: 'TOGGLE_LOADING_SPINNER',
  SHOW_ERROR_TOAST_MESSAGE: 'SHOW_ERROR_TOAST_MESSAGE',
  CLEAR_ERROR_TOAST_MESSAGE: 'CLEAR_ERROR_TOAST_MESSAGE',
  SHOW_TOAST_MESSAGE: 'SHOW_TOAST_MESSAGE',
  SHOW_MULTIPLE_TOAST_MESSAGE: 'SHOW_MULTIPLE_TOAST_MESSAGE',
  SHOW_OPPORTUNITY_UPDATED: 'SHOW_OPPORTUNITY_UPDATED',
  TOGGLE_FORECAST_SAVED: 'TOGGLE_FORECAST_SAVED',
  LOADING_SPINNER_STACK: 'LOADING_SPINNER_STACK'
};
